package Vista;

import Control.*;
import Modelo.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco Luna
 */
public class VentanaModificarEleccion extends javax.swing.JFrame {

    public VentanaModificarEleccion() {
        initComponents();
        setLocationRelativeTo(null);
        cargarElecciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxTipoEleccion = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnEliminarEleccion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbxSeleccionarEleccion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("MODIFICAR ELECCIÓN");

        jLabel2.setText("Fecha (dd/MM/yyyy):");

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo:");

        cbxTipoEleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Municipal", "Nacional", "Referéndum" }));
        cbxTipoEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoEleccionActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnEliminarEleccion.setText("Eliminar");
        btnEliminarEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEleccionActionPerformed(evt);
            }
        });

        jLabel4.setText("Seleccionar Elección:");

        cbxSeleccionarEleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Municipal", "Nacional", "Referéndum", " " }));
        cbxSeleccionarEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeleccionarEleccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 119, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(50, 50, 50)
                .addComponent(btnEliminarEleccion)
                .addGap(51, 51, 51)
                .addComponent(btnRegresar)
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbxSeleccionarEleccion, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTipoEleccion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxSeleccionarEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipoEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnRegresar)
                    .addComponent(btnEliminarEleccion))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTipoEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoEleccionActionPerformed

    }//GEN-LAST:event_cbxTipoEleccionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int index = cbxSeleccionarEleccion.getSelectedIndex();
        if (index < 0 || GestionEleccion.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione una elección válida.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String fechaTexto = txtFecha.getText();
        String nuevoTipo = (String) cbxTipoEleccion.getSelectedItem();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        formatoFecha.setLenient(false);
        try {
            Date nuevaFecha = formatoFecha.parse(fechaTexto);
            Date fechaActual = new Date();
            Eleccion eleccion = GestionEleccion.getLista().get(index);
            if (eleccion.getFecha().before(fechaActual)) {
                JOptionPane.showMessageDialog(this, "No se puede modificar una elección cuya fecha ya ha pasado.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (nuevaFecha.before(fechaActual)) {
                JOptionPane.showMessageDialog(this, "La nueva fecha no puede ser anterior a hoy.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            eleccion.setFecha(nuevaFecha);
            eleccion.setTipo(nuevoTipo);
            JOptionPane.showMessageDialog(this, "Elección modificada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
            cargarElecciones();
        } 
        catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Fecha inválida. Use el formato dd/MM/yyyy.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VentanaGestionElecciones ventanaGestionElecciones = new VentanaGestionElecciones();
        ventanaGestionElecciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnEliminarEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEleccionActionPerformed
        int index = cbxSeleccionarEleccion.getSelectedIndex();
        if (index < 0 || GestionEleccion.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione una elección válida para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar esta elección?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            Eleccion eleccion = GestionEleccion.getLista().get(index);
            GestionEleccion.getLista().remove(eleccion);
            JOptionPane.showMessageDialog(this, "Elección eliminada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            cargarElecciones();
            limpiar();
            if (GestionEleccion.getLista().isEmpty()) {
                cbxSeleccionarEleccion.setSelectedIndex(-1);
            } else {
                cbxSeleccionarEleccion.setSelectedIndex(0);
                cbxSeleccionarEleccionActionPerformed(null);
            }
        }
    }//GEN-LAST:event_btnEliminarEleccionActionPerformed

    private void cbxSeleccionarEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeleccionarEleccionActionPerformed
        int index = cbxSeleccionarEleccion.getSelectedIndex();
        if (index >= 0 && !GestionEleccion.getLista().isEmpty()) {
            Eleccion eleccion = GestionEleccion.getLista().get(index);
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
            txtFecha.setText(formatoFecha.format(eleccion.getFecha()));
            cbxTipoEleccion.setSelectedItem(eleccion.getTipo());
        }
    }//GEN-LAST:event_cbxSeleccionarEleccionActionPerformed

    public void cargarElecciones() {
        cbxSeleccionarEleccion.removeAllItems();
        LinkedList<Eleccion> lista = GestionEleccion.getLista();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        if (lista.isEmpty()) {
            cbxSeleccionarEleccion.addItem("No hay elecciones disponibles");
            cbxSeleccionarEleccion.setEnabled(false);
            txtFecha.setEnabled(false);
            cbxTipoEleccion.setEnabled(false);
            return;
        }
        cbxSeleccionarEleccion.setEnabled(true);
        txtFecha.setEnabled(true);
        cbxTipoEleccion.setEnabled(true);
        for (Eleccion eleccion : lista) {
            String eleccionTexto = formatoFecha.format(eleccion.getFecha()) + " - " + eleccion.getTipo();
            cbxSeleccionarEleccion.addItem(eleccionTexto);
        }
    }

    public void limpiar() {
        txtFecha.setText("");
        cbxTipoEleccion.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaModificarEleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarEleccion;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxSeleccionarEleccion;
    private javax.swing.JComboBox<String> cbxTipoEleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
