/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.util.LinkedList;
import Control.*;
import Modelo.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco Luna
 */
public class VentanaModificarCandidato extends javax.swing.JFrame {

    /**
     * Creates new form VentanaModificarCandidato
     */
    public VentanaModificarCandidato() {
        initComponents();
        setLocationRelativeTo(null);
        txtNombre.setEditable(false);
        txtApellidoPaterno.setEditable(false);
        txtApellidoMaterno.setEditable(false);
        txtDNI.setEditable(false);
        txtPartido.setEditable(false);
        cargarCandidatos();
        if (cbxSeleccionarCandidato.getItemCount() > 0) {
            cbxSeleccionarCandidato.setSelectedIndex(0);
            cargarDatosCandidato(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hola = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPartido = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbxSeleccionarCandidato = new javax.swing.JComboBox<>();
        btnModificarNombre = new javax.swing.JButton();
        btnModificarAP = new javax.swing.JButton();
        btnModificarAM = new javax.swing.JButton();
        btnModificarDNI = new javax.swing.JButton();
        btnModificarPartido = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("MODIFICAR CANDIDATO");

        hola.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellido Paterno");

        txtApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoActionPerformed(evt);
            }
        });

        jLabel5.setText("Apellido Materno");

        jLabel3.setText("DNI");

        jLabel4.setText("Partido Politico");

        jLabel13.setText("Seleccionar Candidato:");

        cbxSeleccionarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeleccionarCandidatoActionPerformed(evt);
            }
        });

        btnModificarNombre.setText("Modificar");
        btnModificarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarNombreActionPerformed(evt);
            }
        });

        btnModificarAP.setText("Modificar");
        btnModificarAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAPActionPerformed(evt);
            }
        });

        btnModificarAM.setText("Modificar");
        btnModificarAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAMActionPerformed(evt);
            }
        });

        btnModificarDNI.setText("Modificar");
        btnModificarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDNIActionPerformed(evt);
            }
        });

        btnModificarPartido.setText("Modificar");
        btnModificarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPartidoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hola)
                                .addComponent(jLabel2))
                            .addGap(79, 79, 79))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3))
                            .addGap(75, 75, 75)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13))
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtDNI, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxSeleccionarCandidato, javax.swing.GroupLayout.Alignment.LEADING, 0, 275, Short.MAX_VALUE)
                    .addComponent(txtPartido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificarNombre)
                    .addComponent(btnModificarAP)
                    .addComponent(btnModificarAM)
                    .addComponent(btnModificarDNI)
                    .addComponent(btnModificarPartido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addGap(173, 173, 173))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbxSeleccionarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hola)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarNombre))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarAP))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarAM))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnModificarDNI))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnModificarPartido))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnRegresar)
                    .addComponent(btnGuardar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void cbxSeleccionarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeleccionarCandidatoActionPerformed
        int index = cbxSeleccionarCandidato.getSelectedIndex();
        if (index >= 0) {
            cargarDatosCandidato(index);
        }
    }//GEN-LAST:event_cbxSeleccionarCandidatoActionPerformed

    private void txtApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPaternoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int index = cbxSeleccionarCandidato.getSelectedIndex();
        if (index >= 0) {
            String dni = txtDNI.getText();
            if (!dni.matches("\\d{8}")) {
                JOptionPane.showMessageDialog(this, "El DNI debe ser un número de 8 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Candidato candidato = GestionCandidato.getLista().get(index);
            candidato.setNombre(txtNombre.getText());
            candidato.setApellidoPaterno(txtApellidoPaterno.getText());
            candidato.setApellidoMaterno(txtApellidoMaterno.getText());
            candidato.setDNI(dni);
            candidato.setPartidoPolitico(txtPartido.getText());
            JOptionPane.showMessageDialog(this, "Candidato actualizado correctamente.");
            txtNombre.setEditable(false);
            txtApellidoPaterno.setEditable(false);
            txtApellidoMaterno.setEditable(false);
            txtDNI.setEditable(false);
            txtPartido.setEditable(false);
            cargarCandidatos();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int index = cbxSeleccionarCandidato.getSelectedIndex();
        if (index >= 0) {
            int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este candidato?");
            if (confirm == JOptionPane.YES_OPTION) {
                GestionCandidato.getLista().remove(index);
                JOptionPane.showMessageDialog(this, "Candidato eliminado correctamente.");
                cargarCandidatos();
                limpiar();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VentanaGestionElecciones ventanaGestionElecciones = new VentanaGestionElecciones();
        ventanaGestionElecciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnModificarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarNombreActionPerformed
        txtNombre.setEditable(true);
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnModificarNombreActionPerformed

    private void btnModificarAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAPActionPerformed
        txtApellidoPaterno.setEditable(true);
        txtApellidoPaterno.requestFocus();
    }//GEN-LAST:event_btnModificarAPActionPerformed

    private void btnModificarAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAMActionPerformed
        txtApellidoMaterno.setEditable(true);
        txtApellidoMaterno.requestFocus();
    }//GEN-LAST:event_btnModificarAMActionPerformed

    private void btnModificarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDNIActionPerformed
        txtDNI.setEditable(true);
        txtDNI.requestFocus();
    }//GEN-LAST:event_btnModificarDNIActionPerformed

    private void btnModificarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPartidoActionPerformed
        txtPartido.setEditable(true);
        txtPartido.requestFocus();
    }//GEN-LAST:event_btnModificarPartidoActionPerformed

    private void cargarCandidatos() {
        cbxSeleccionarCandidato.removeAllItems();
        LinkedList<Candidato> lista = GestionCandidato.getLista();
        if (lista.isEmpty()) {
            cbxSeleccionarCandidato.addItem("No hay candidatos disponibles");
        } else {
            for (Candidato candidato : lista) {
                cbxSeleccionarCandidato.addItem(candidato.getNombre() + " " + candidato.getApellidoPaterno() + " " + candidato.getApellidoMaterno());
            }
        }
    }

    private void cargarDatosCandidato(int index) {
        LinkedList<Candidato> lista = GestionCandidato.getLista();
        if (index >= 0 && index < lista.size()) {
            Candidato candidato = lista.get(index);
            txtNombre.setText(candidato.getNombre());
            txtApellidoPaterno.setText(candidato.getApellidoPaterno());
            txtApellidoMaterno.setText(candidato.getApellidoMaterno());
            txtDNI.setText(candidato.getDNI());
            txtPartido.setText(candidato.getPartidoPolitico());
        }
    }
    
    private void limpiar() {
        txtNombre.setText("");
        txtApellidoPaterno.setText("");
        txtApellidoMaterno.setText("");
        txtDNI.setText("");
        txtPartido.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaModificarCandidato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificarAM;
    private javax.swing.JButton btnModificarAP;
    private javax.swing.JButton btnModificarDNI;
    private javax.swing.JButton btnModificarNombre;
    private javax.swing.JButton btnModificarPartido;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxSeleccionarCandidato;
    private javax.swing.JLabel hola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPartido;
    // End of variables declaration//GEN-END:variables
}
