/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.util.LinkedList;
import Control.*;
import Modelo.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco Luna
 */
public class VentanaReportes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaReportes
     */
    public VentanaReportes() {
        initComponents();
        setLocationRelativeTo(null);
        cargarElecciones();
        txtIdActa.setEditable(false);
        txtTitulo.setEditable(false);
        txtVotantesRegistrados.setEditable(false);
        txtVotantesEfectivos.setEditable(false);
        txtVotosBlancos.setEditable(false);
        txtVotosNulos.setEditable(false);
        txtVotosCandidatos.setEditable(false);
        txtObservacion.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbxSeleccionarCandidato = new javax.swing.JComboBox<>();
        cbxSeleccionarMesa = new javax.swing.JComboBox<>();
        cbxSeleccionarEleccion = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnCambiarObservaciones = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        txtIdActa = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtVotantesRegistrados = new javax.swing.JTextField();
        txtVotantesEfectivos = new javax.swing.JTextField();
        txtVotosBlancos = new javax.swing.JTextField();
        txtVotosNulos = new javax.swing.JTextField();
        txtVotosCandidatos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("REPORTES DE ELECCIONES  ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Seleccionar Elección:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Seleccionar Mesa:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Seleccionar Candidato:");

        cbxSeleccionarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeleccionarCandidatoActionPerformed(evt);
            }
        });

        cbxSeleccionarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeleccionarMesaActionPerformed(evt);
            }
        });

        cbxSeleccionarEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeleccionarEleccionActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Votos por Candidato");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Votantes Registrados");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Votantes Efectivos");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Votos Blancos");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Votos Nulos");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Observaciones");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnCambiarObservaciones.setText("Cambiar observación");

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane1.setViewportView(txtObservacion);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Id Acta");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Título");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel20)
                    .addComponent(jLabel5)
                    .addComponent(jLabel21)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(btnCambiarObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxSeleccionarCandidato, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(txtVotantesRegistrados, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVotantesEfectivos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVotosBlancos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxSeleccionarEleccion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxSeleccionarMesa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdActa)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVotosCandidatos)
                    .addComponent(txtVotosNulos, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSeleccionarEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSeleccionarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdActa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSeleccionarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVotosCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVotantesRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVotantesEfectivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVotosBlancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVotosNulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(btnCambiarObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(btnRegresar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSeleccionarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeleccionarCandidatoActionPerformed
        int indexEleccion = cbxSeleccionarEleccion.getSelectedIndex();
        int indexMesa = cbxSeleccionarMesa.getSelectedIndex();
        int indexCandidato = cbxSeleccionarCandidato.getSelectedIndex();
        if (indexEleccion >= 0 && indexMesa >= 0 && indexCandidato >= 0) {
            LinkedList<Eleccion> elecciones = GestionEleccion.getLista();
            Eleccion eleccion = elecciones.get(indexEleccion);
            MesaElectoral mesa = eleccion.getMesas().get(indexMesa);
            ActaElectoral acta = mesa.getActa();
            if (acta != null) {
                Candidato candidato = eleccion.getCandidatos().get(indexCandidato);
                int votosCandidato = 0;
                for (VotoCandidato vc : acta.getVotosPorCandidato()) {
                    if (vc.getCandidato().equals(candidato)) {
                        votosCandidato = vc.getVotos();
                        break;
                    }
                }
                txtVotosCandidatos.setText(String.valueOf(votosCandidato));
            } else {
                JOptionPane.showMessageDialog(this, "No hay un acta asociada a la mesa seleccionada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cbxSeleccionarCandidatoActionPerformed

    private void cbxSeleccionarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeleccionarMesaActionPerformed
        int indexEleccion = cbxSeleccionarEleccion.getSelectedIndex();
        int indexMesa = cbxSeleccionarMesa.getSelectedIndex();
        cargarDatosMesa(indexEleccion, indexMesa);
    }//GEN-LAST:event_cbxSeleccionarMesaActionPerformed

    private void cbxSeleccionarEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeleccionarEleccionActionPerformed
        int indexEleccion = cbxSeleccionarEleccion.getSelectedIndex();
        cargarMesas(indexEleccion);
    }//GEN-LAST:event_cbxSeleccionarEleccionActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MiembroMesa usuarioActivo = SesionActiva.getUsuarioActivo();
        if (usuarioActivo != null && usuarioActivo instanceof MiembroMesa) {
            VentanaPrincipalMiembroMesa ventanaMiembro = new VentanaPrincipalMiembroMesa();
            ventanaMiembro.setVisible(true);
            this.dispose();
        } else {
            VentanaPrincipalAdmin ventanaAdmin = new VentanaPrincipalAdmin();
            ventanaAdmin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cargarElecciones() {
        cbxSeleccionarEleccion.removeAllItems();
        LinkedList<Eleccion> elecciones = GestionEleccion.getLista();
        if (elecciones.isEmpty()) {
            cbxSeleccionarEleccion.addItem("No hay elecciones disponibles");
        } else {
            for (Eleccion eleccion : elecciones) {
                cbxSeleccionarEleccion.addItem(eleccion.getTipo());
            }
        }
    }

    private void cargarMesas(int indexEleccion) {
        cbxSeleccionarMesa.removeAllItems();
        LinkedList<Eleccion> elecciones = GestionEleccion.getLista();
        if (indexEleccion >= 0 && indexEleccion < elecciones.size()) {
            Eleccion eleccion = elecciones.get(indexEleccion);
            for (MesaElectoral mesa : eleccion.getMesas()) {
                cbxSeleccionarMesa.addItem("Mesa " + mesa.getNumero());
            }
        }
    }

    private void cargarDatosMesa(int indexEleccion, int indexMesa) {
        LinkedList<Eleccion> elecciones = GestionEleccion.getLista();
        cbxSeleccionarCandidato.removeAllItems();
        if (indexEleccion >= 0 && indexEleccion < elecciones.size()) {
            Eleccion eleccion = elecciones.get(indexEleccion);
            if (indexMesa >= 0 && indexMesa < eleccion.getMesas().size()) {
                MesaElectoral mesa = eleccion.getMesas().get(indexMesa);
                ActaElectoral acta = mesa.getActa();
                if (acta != null) {
                    txtIdActa.setText(acta.getIdActa());
                    txtTitulo.setText(acta.getTitulo());
                    txtVotantesRegistrados.setText(String.valueOf(acta.getTotalVotantesRegistrados()));
                    txtVotantesEfectivos.setText(String.valueOf(acta.getTotalVotantesEfectivos()));
                    txtVotosBlancos.setText(String.valueOf(acta.getVotosBlancos()));
                    txtVotosNulos.setText(String.valueOf(acta.getVotosNulos()));
                    txtObservacion.setText(String.join("\n", acta.getObservaciones()));
                } else {
                    limpiar();
                }
                for (Candidato candidato : eleccion.getCandidatos()) {
                    cbxSeleccionarCandidato.addItem(candidato.getNombre() + " " + candidato.getApellidoPaterno());
                }
            }
        }
    }

    private void limpiar() {
        txtIdActa.setText("");
        txtTitulo.setText("");
        txtVotantesRegistrados.setText("");
        txtVotantesEfectivos.setText("");
        txtVotosBlancos.setText("");
        txtVotosNulos.setText("");
        txtObservacion.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarObservaciones;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxSeleccionarCandidato;
    private javax.swing.JComboBox<String> cbxSeleccionarEleccion;
    private javax.swing.JComboBox<String> cbxSeleccionarMesa;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdActa;
    private javax.swing.JTextArea txtObservacion;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtVotantesEfectivos;
    private javax.swing.JTextField txtVotantesRegistrados;
    private javax.swing.JTextField txtVotosBlancos;
    private javax.swing.JTextField txtVotosCandidatos;
    private javax.swing.JTextField txtVotosNulos;
    // End of variables declaration//GEN-END:variables
}
